name: ssh
version: 1.0.0+0
description: Command line SSH client with dartssh.
author: Green Appers, Inc. <greenappers@gmail.com>
homepage: https://github.com/GreenAppers/cruzawl
documentation: https://pub.dev/documentation/dartssh/latest/

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  args: ^1.5.2
  dartssh:
    path: ../
  tweetnacl:
    git:
      url: https://github.com/muriloventuroso/tweetnacl-dart
      ref: af4c5305a40b727a9ab7d16e4ab402009c0a8b51
  stack_trace: ^1.9.3
