name: dartssh
version: 1.0.4+4
description: Dart SSH package providing First-class tunnelling primitives.
author: Green Appers, Inc. <greenappers@gmail.com>
homepage: https://github.com/GreenAppers/dartssh

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  asn1lib: ^1.0.0
  convert: ^3.0.0
  meta: ^1.1.6
  http: ^0.13.0
  pedantic: ^1.8.0
  pointycastle: ^3.0.1
  cryptography: ^2.0.1
  pinenacl:
    git:
      url: https://github.com/ilap/pinenacl-dart.git
      ref: sealed-class-restriction
  validators: ^3.0.0

dev_dependencies:
  build_runner: ^2.0.4
  test: ^1.6.5
